name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Benchmark:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Benchmark
      run: dotnet run -c Release --filter * --project ConsoleApp1
#    - name: Upload benchmark results
#      uses: actions/upload-artifact@v2
#      with:
#        name: Benchmark_Results
#        path: ./BenchmarkDotNet.Artifacts/results/*
    - name: Upload results
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://outsystems-dev.kb22a9gnkn.outsystemsteams.com/BenchSystems/rest/v1/reports'
        method: 'POST'
        data: '{}'
